
language: java
dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script: mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash .travis/release.sh
  on:
    tags: true
    branch: release